databases:
  - name: atone_no_shiren_app_DB
    databaseName: atone_no_shiren_app_db
    user: atone_no_shiren_app
    region: singapore

services:
  - type: web
    name: atone_no_shiren_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: atone_no_shiren_app_DB
          property: connectionString
      # - key: RAILS_MASTER_KEY
      #   sync: false