# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29115db6620eadce6da05a94ab12c3f11b844066e8fd22df95d66e2a60c20e5ee4ed7fb807e0b2f242e0c7b3152f970446fdc5caa7a3ff02db252b454e9d0b80

test:
  secret_key_base: d023c7e9d8b75345926cc8f9ebcec45c8791b7b4b1cf5c94feb5537818dd8e22949a81932b8b78bd991acdf40373d6f9b181edd67e75a4e42f29b5376a1461e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
